version: "3.9"

services:
  rest:
    build:
      context: .
      dockerfile: DOCKERFILE.REST
    container_name: rest-server
    restart: always
#    environment:
 #     DATABASE_HOST: postgres
  #    DATABASE_PORT: 5432
   #   DATABASE_NAME: documentdb
    #  DATABASE_USER: myuser
     # DATABASE_PASSWORD: mypassword
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: documentdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
