# Let Spring Batch create metadata tables
spring.batch.jdbc.initialize-schema=always

# JPA (used only for Batch metadata, not your domain)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
