spring.datasource.url=jdbc:postgresql://postgres:5432/documentdb
spring.datasource.username=batchuser
spring.datasource.password=batchpassword

spring.batch.job.enabled=true

spring.batch.jdbc.initialize-schema=always
spring.batch.jdbc.schema=classpath:org/springframework/batch/core/schema-postgresql.sql
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
